package proj.utility;

public interface AppConstants {
	String ACCOUNT = "ACCOUNT";
	String BALANCE = "BALANCE";
	int INCOME = 0;
	int Expense = 1;
	int BILLPAID = 1;
	int BILLNOPAID = 0;
	int ISREMINDER = 1;
	int NOREMINDER = 0;
	String PIGGYBANKSAHREDPREFERNECE="PIGGYBANKSAHREDPREFERNECE";
	int ACTIVESTATUS=0;
	int INACTIVESTATUS=1;
	String TABLETRANSACTION="TRANSACTIONS";
	String TABLEACCOUNTS="ACCOUNTS";
	String TABLEBILLS="BILLS";
	String BILL="BILL";
	String TRANSACTION="TRANSACTION";
	String DAILYLIMIT="DAILYLIMIT";
	String WEEKLYLIMIT="WEEKLYLIMIT";
	String MONTHLYLIMIT="MONTHLYLIMIT";
	String YEARLYLIMIT="YEARLYLIMIT";
	String GREENCOLOR="GREENCOLOR";
	String YELLOWCOLOR="YELLOWCOLOR";
	String BLUECOLOR="BLUECOLOR";
	String ORANGENCOLOR="ORANGENCOLOR";
	String PURPLECOLOR="PURPLECOLOR";
	String PINKCOLOR="PINKCOLOR";
	String BACKGROUNDCOLOR="BACKGROUNDCOLOR";
	String BILLNAME = "BILLNAME";
	String BILLAMOUNT = "BILLAMOUNT";
	
}
